=== goldmansachs/jdmn/dmn-core/src/main/resources/tck/testCases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (x64) (http://www.altova.com) by Bruce Silver (private) -->
<xs:schema xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.omg.org/spec/DMN/20160719/testcase" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="testCaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="decision"/>
			<xs:enumeration value="bkm"/>
			<xs:enumeration value="decisionService"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="testCases">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="modelName" type="xs:string" minOccurs="0"/>
				<xs:element name="labels" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="testCase" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="inputNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="valueType">
											<xs:attribute name="name" use="required"/>
											<xs:attribute name="namespace" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="resultNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="expected" type="valueType" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="errorResult" type="xs:boolean" default="false"/>
									<xs:attribute name="name" use="required"/>
									<xs:attribute name="namespace" type="xs:string" use="optional"/>
									<xs:attribute name="type" type="xs:string"/>
									<xs:anyAttribute namespace="##other" processContents="lax"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="extensionElements" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string"/>
						<xs:attribute name="type" type="testCaseType" default="decision"/>
						<xs:attribute name="invocableName" type="xs:string"/> <!-- if type==decisionService, this attribute will point at which DS to invoke. -->
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="namespace" type="xs:string" use="optional"/>
						<xs:anyAttribute namespace="##other" processContents="lax"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string" use="optional"/>
			<xs:anyAttribute namespace="##other" processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="valueType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="value" type="xs:anySimpleType" nillable="true"/>
				<xs:element name="component" nillable="true" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="valueType">
								<xs:attribute name="name" />
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="list" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" type="valueType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="extensionElements" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
</xs:schema>

=== goldmansachs/jdmn/dmn-test-cases/standard/tck/1.1/cl3/0007-date-time/translator/standard/0007-date-time-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<modelName>0007-date-time.dmn</modelName>
	<labels>
		<label>Compliance Level 3</label>
		<label>Literal Expression</label>
		<label>Context</label>
		<label>Item Definition</label>
		<label>FEEL Functions: date and time</label>
		<label>FEEL Arithmetic</label>
		<label>FEEL Special-character Names</label>
		<label>Data Type: String</label>
		<label>Data Type: Number</label>
		<label>Data Type: Structure</label>
		<label>Data Type: Date</label>
		<label>Data Type: Time</label>
	</labels>
	<testCase id="001">
		<inputNode name="dateString">
			<value xsi:type="xsd:string">2015-12-24</value>
		</inputNode>
		<inputNode name="timeString">
			<value xsi:type="xsd:string">00:00:01-01:00</value>
		</inputNode>
		<inputNode name="dateTimeString">
			<value xsi:type="xsd:string">2016-12-24T23:59:00-08:00</value>
		</inputNode>
		<inputNode name="Hours">
			<value xsi:type="xsd:decimal">12</value>
		</inputNode>
		<inputNode name="Minutes">
			<value xsi:type="xsd:decimal">59</value>
		</inputNode>
		<inputNode name="Seconds">
			<value xsi:type="xsd:decimal">01.3</value>
		</inputNode>
		<inputNode name="Timezone">
			<value xsi:type="xsd:duration">-PT1H</value>
		</inputNode>
		<inputNode name="Year">
			<value xsi:type="xsd:decimal">1999</value>
		</inputNode>
		<inputNode name="Month">
			<value xsi:type="xsd:decimal">11</value>
		</inputNode>
		<inputNode name="Day">
			<value xsi:type="xsd:decimal">22</value>
		</inputNode>
		<inputNode name="oneHour">
			<value xsi:type="xsd:duration">PT1H</value>
		</inputNode>
		<inputNode name="durationString">
			<value xsi:type="xsd:string">P13DT2H14S</value>
		</inputNode>
		<resultNode name="Date-Time" type="decision">
			<expected>
				<value xsi:type="xsd:dateTime">2016-12-24T23:59:00-08:00</value>
			</expected>
		</resultNode>
		<resultNode name="Date" type="decision">
			<expected>
				<component name="fromString">
					<value xsi:type="xsd:date">2015-12-24</value>
				</component>
				<component name="fromDateTime">
					<value xsi:type="xsd:date">2016-12-24</value>
				</component>
				<component name="fromYearMonthDay">
					<value xsi:type="xsd:date">1999-11-22</value>
				</component>
			</expected>
		</resultNode>
		<resultNode name="Time" type="decision">
			<expected>
				<value xsi:type="xsd:time">00:00:01-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="Date-Time2" type="decision">
			<expected>
				<value xsi:type="xsd:dateTime">2015-12-24T00:00:01-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="Time2" type="decision">
			<expected>
				<value xsi:type="xsd:time">00:00:01-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="Time3" type="decision">
			<expected>
				<value xsi:type="xsd:time">12:59:01.3-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="dtDuration1" type="decision">
			<expected>
				<value xsi:type="xsd:duration">P13DT2H14S</value>
			</expected>
		</resultNode>
		<resultNode name="dtDuration2" type="decision">
			<expected>
				<value xsi:type="xsd:duration">P367DT6H58M59S</value>
			</expected>
		</resultNode>
		<resultNode name="sumDurations" type="decision">
			<expected>
				<value xsi:type="xsd:duration">P380DT8H59M13S</value>
			</expected>
		</resultNode>
		<resultNode name="ymDuration2" type="decision">
			<expected>
				<value xsi:type="xsd:duration">P1Y0M</value>
			</expected>
		</resultNode>
		<resultNode name="cDay" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">24</value>
			</expected>
		</resultNode>
		<resultNode name="cYear" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">2015</value>
			</expected>
		</resultNode>
		<resultNode name="cMonth" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">12</value>
			</expected>
		</resultNode>
		<resultNode name="cHour" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">0</value>
			</expected>
		</resultNode>
		<resultNode name="cMinute" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">0</value>
			</expected>
		</resultNode>
		<resultNode name="cSecond" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">1</value>
			</expected>
		</resultNode>
		<resultNode name="cOffset" type="decision">
			<expected>
				<value xsi:type="xsd:duration">-PT1H</value>
			</expected>
		</resultNode>
		<resultNode name="years" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">1</value>
			</expected>
		</resultNode>
		<resultNode name="seconds" type="decision">
			<expected>
				<value xsi:type="xsd:decimal">14</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== goldmansachs/jdmn/dmn-test-cases/standard/tck/1.2/nc/0019-flight-rebooking/0019-flight-rebooking-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0019-flight-rebooking.dmn</modelName>
    <labels>
        <label>Compliance Level 3</label>
        <label>Literal Expression</label>
        <label>Item Definition</label>
        <label>Context</label>
        <label>Function Invocation</label>
        <label>Business Knowledge Model</label>
        <label>Decision Table: Single Output</label>
        <label>Hit Policy: UNIQUE</label>
        <label>FEEL Filter (10.3.2.5)</label>
        <label>FEEL Conditionals</label>
        <label>FEEL List</label>
        <label>FEEL Relation</label>
    </labels>
    <testCase id="001">
		<inputNode name="Flight List">
			<list>
				<item>
					<component name="Flight Number"><value>UA123</value></component>
					<component name="From"><value>SFO</value></component>
					<component name="To"><value>SNA</value></component>
					<component name="Departure"><value>2017-01-01T18:00:00</value></component>
					<component name="Arrival"><value>2017-01-01T19:00:00</value></component>
					<component name="Capacity"><value>5</value></component>
					<component name="Status"><value>cancelled</value></component>
				</item>
				<item>
					<component name="Flight Number"><value>UA456</value></component>
					<component name="From"><value>SFO</value></component>
					<component name="To"><value>SNA</value></component>
					<component name="Departure"><value>2017-01-01T19:00:00</value></component>
					<component name="Arrival"><value>2017-01-01T20:00:00</value></component>
					<component name="Capacity"><value>2</value></component>
					<component name="Status"><value>scheduled</value></component>
				</item>
				<item>
					<component name="Flight Number"><value>UA789</value></component>
					<component name="From"><value>SFO</value></component>
					<component name="To"><value>SNA</value></component>
					<component name="Departure"><value>2017-01-01T21:00:00</value></component>
					<component name="Arrival"><value>2017-01-01T23:00:00</value></component>
					<component name="Capacity"><value>2</value></component>
					<component name="Status"><value>scheduled</value></component>
				</item>
				<item>
					<component name="Flight Number"><value>UA1001</value></component>
					<component name="From"><value>SFO</value></component>
					<component name="To"><value>SNA</value></component>
					<component name="Departure"><value>2017-01-01T23:00:00</value></component>
					<component name="Arrival"><value>2017-01-02T05:00:00</value></component>
					<component name="Capacity"><value>0</value></component>
					<component name="Status"><value>scheduled</value></component>
				</item>
				<item>
					<component name="Flight Number"><value>UA1111</value></component>
					<component name="From"><value>SFO</value></component>
					<component name="To"><value>LAX</value></component>
					<component name="Departure"><value>2017-01-01T23:00:00</value></component>
					<component name="Arrival"><value>2017-01-02T05:00:00</value></component>
					<component name="Capacity"><value>2</value></component>
					<component name="Status"><value>scheduled</value></component>
				</item>
			</list>
		</inputNode>
		<inputNode name="Passenger List">
			<list>
				<item>
					<component name="Name"><value>Tom</value></component>
					<component name="Status"><value>bronze</value></component>
					<component name="Miles"><value>10</value></component>
					<component name="Flight Number"><value>UA123</value></component>
				</item>
				<item>
					<component name="Name"><value>Igor</value></component>
					<component name="Status"><value>gold</value></component>
					<component name="Miles"><value>50000</value></component>
					<component name="Flight Number"><value>UA123</value></component>
				</item>
				<item>
					<component name="Name"><value>Jenny</value></component>
					<component name="Status"><value>gold</value></component>
					<component name="Miles"><value>500000</value></component>
					<component name="Flight Number"><value>UA123</value></component>
				</item>
				<item>
					<component name="Name"><value>Harry</value></component>
					<component name="Status"><value>gold</value></component>
					<component name="Miles"><value>100000</value></component>
					<component name="Flight Number"><value>UA123</value></component>
				</item>
				<item>
					<component name="Name"><value>Dick</value></component>
					<component name="Status"><value>silver</value></component>
					<component name="Miles"><value>100</value></component>
					<component name="Flight Number"><value>UA123</value></component>
				</item>
			</list>
		</inputNode>
		<resultNode name="Rebooked Passengers">
			<expected>
				<list>
					<item>
						<component name="Name"><value>Jenny</value></component>
						<component name="Status"><value>gold</value></component>
						<component name="Miles"><value>500000</value></component>
						<component name="Flight Number"><value>UA456</value></component>
					</item>
					<item>
						<component name="Name"><value>Harry</value></component>
						<component name="Status"><value>gold</value></component>
						<component name="Miles"><value>100000</value></component>
						<component name="Flight Number"><value>UA456</value></component>
					</item>
					<item>
						<component name="Name"><value>Igor</value></component>
						<component name="Status"><value>gold</value></component>
						<component name="Miles"><value>50000</value></component>
						<component name="Flight Number"><value>UA789</value></component>
					</item>
					<item>
						<component name="Name"><value>Dick</value></component>
						<component name="Status"><value>silver</value></component>
						<component name="Miles"><value>100</value></component>
						<component name="Flight Number"><value>UA789</value></component>
					</item>
					<item>
						<component name="Name"><value>Tom</value></component>
						<component name="Status"><value>bronze</value></component>
						<component name="Miles"><value>10</value></component>
						<component name="Flight Number"><value/></component>
					</item>
				</list>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== goldmansachs/jdmn/dmn-test-cases/composite/1.2/0004-decision-tables/translator/0017-tableTests-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases
		xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		namespace="http://www.provider.com/definitions/decisions"
>
	<modelName>decisionTables</modelName>
	<testCase id="001">
		<inputNode name="structA" namespace="http://www.provider.com/definitions/decision-inputs">
			<component name="name">
				<value xsi:type="xsd:string">widget</value>
			</component>
			<component name="price">
				<value xsi:type="xsd:decimal">20</value>
			</component>
		</inputNode>
		<resultNode name="priceGt10" type="decision">
			<expected>
				<value xsi:type="xsd:boolean">true</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="002">
		<inputNode name="structA" namespace="http://www.provider.com/definitions/decision-inputs">
			<component name="name">
				<value xsi:type="xsd:string">widget</value>
			</component>
			<component name="price">
				<value xsi:type="xsd:decimal">20</value>
			</component>
		</inputNode>
		<inputNode name="numB" namespace="http://www.provider.com/definitions/decision-inputs">
			<value xsi:type="xsd:decimal">9</value>
		</inputNode>
		<inputNode name="numC" namespace="http://www.provider.com/definitions/decision-inputs">
			<value xsi:type="xsd:decimal">10</value>
		</inputNode>
		<resultNode name="priceInRange" type="decision">
			<expected>
				<value xsi:type="xsd:string">Not in range</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="003">
		<inputNode name="dateD" namespace="http://www.provider.com/definitions/decision-inputs">
			<value xsi:type="xsd:date">2016-11-01</value>
		</inputNode>
		<resultNode name="dateCompare1" type="decision">
			<expected>
				<value xsi:type="xsd:boolean">true</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="004">
		<inputNode name="dateD" namespace="http://www.provider.com/definitions/decision-inputs">
			<value xsi:type="xsd:date">2016-11-01</value>
		</inputNode>
		<inputNode name="dateE" namespace="http://www.provider.com/definitions/decision-inputs">
			<value xsi:type="xsd:date">2016-11-02</value>
		</inputNode>
		<resultNode name="dateCompare2" type="decision">
			<expected>
				<value xsi:type="xsd:boolean">false</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== goldmansachs/jdmn/dmn-tck-integration-tests/src/main/resources/tck/cl3/double-mixed/0002-string-functions-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<modelName>0002-string-functions.dmn</modelName>
	<labels>
		<label>Compliance Level 3</label>
		<label>Literal Expression</label>
		<label>Context</label>
		<label>Item Definition</label>
		<label>FEEL Functions: strings</label>
		<label>FEEL Arithmetic</label>
		<label>FEEL Filter (10.3.2.5)</label>
		<label>FEEL Functions: string</label>
		<label>FEEL Functions: string</label>
		<label>Data Type: String</label>
		<label>Data Type: Number</label>
		<label>Data Type: Boolean</label>
		<label>Data Type: Structure</label>
	</labels>
	<testCase id="001">
		<description>Tests FEEL built-in functions on string literals (starts_with, ends_with, contains, substring, string_length, upper_case, lower_case, substring_before, substring_after)</description>
		<inputNode name="A">
			<value xsi:type="xsd:string">banana</value>
		</inputNode>
		<inputNode name="B">
			<value xsi:type="xsd:string">a</value>
		</inputNode>
		<inputNode name="NumC">
			<value xsi:type="xsd:decimal">2</value>
		</inputNode>
		<resultNode name="Basic" type="decision">
			<expected>
				<component name="startsWithX">
					<value xsi:type="xsd:boolean">false</value>
				</component>
				<component name="startsWithB">
					<value xsi:type="xsd:boolean">false</value>
				</component>
				<component name="endsWithX">
					<value xsi:type="xsd:boolean">false</value>
				</component>
				<component name="endsWithB">
					<value xsi:type="xsd:boolean">true</value>
				</component>
				<component name="containsX">
					<value xsi:type="xsd:boolean">false</value>
				</component>
				<component name="containsB">
					<value xsi:type="xsd:boolean">true</value>
				</component>
				<component name="substringC1">
					<value xsi:type="xsd:string">a</value>
				</component>
				<component name="stringlength">
					<value xsi:type="xsd:decimal">6</value>
				</component>
				<component name="uppercase">
					<value xsi:type="xsd:string">BANANA</value>
				</component>
				<component name="lowercase">
					<value xsi:type="xsd:string">a</value>
				</component>
				<component name="substringBeforeB">
					<value xsi:type="xsd:string">b</value>
				</component>
				<component name="substringAfterB">
					<value xsi:type="xsd:string">nana</value>
				</component>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="002">
		<description>Tests FEEL built-in function for regular expresssion matching (matches)</description>
		<inputNode name="A">
			<value xsi:type="xsd:string">banana</value>
		</inputNode>
		<resultNode name="Matches" type="decision">
			<expected>
				<value xsi:type="xsd:boolean">true</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="003">
		<description>Tests FEEL built-in function 'replace' on string literals</description>
		<inputNode name="A">
			<value xsi:type="xsd:string">banana</value>
		</inputNode>
		<resultNode name="Replace" type="decision">
			<expected>
				<component name="Aao">
					<value xsi:type="xsd:string">bonono</value>
				</component>
				<component name="AanplusStarstar">
					<value xsi:type="xsd:string">b**a</value>
				</component>
				<component name="encloseVowels">
					<value xsi:type="xsd:string">b[a]n[a]n[a]</value>
				</component>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="004">
		<description>Tests FEEL built-in function for converting a number to a string</description>
		<inputNode name="NumC">
			<value xsi:type="xsd:decimal">2</value>
		</inputNode>
		<resultNode name="Constructor" type="decision">
			<expected>
				<value xsi:type="xsd:string">2</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== goldmansachs/jdmn/dmn-test-cases/tck/1.1/cl3/0017-tableTests/0017-tableTests-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<modelName>0017-tableTests.dmn</modelName>
	<labels>
		<label>Compliance Level 3</label>
		<label>Literal Expression</label>
		<label>Item Definition</label>
		<label>Decision Table: Single Output</label>
		<label>Hit Policy: UNIQUE</label>
		<label>Hit Policy: PRIORITY</label>
		<label>FEEL Arithmetic</label>
		<label>FEEL Functions: date and time</label>
		<label>Data Type: String</label>
		<label>Data Type: Number</label>
		<label>Data Type: Boolean</label>
		<label>Data Type: Structure</label>
		<label>Data Type: Collection</label>
		<label>Data Type: Date</label>
	</labels>
	<testCase id="001">
		<inputNode name="structA">
			<component name="name">
				<value>widget</value>
			</component>
			<component name="price">
				<value>20</value>
			</component>
		</inputNode>
		<resultNode name="priceGt10" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="002">
		<inputNode name="structA">
			<component name="name">
				<value>widget</value>
			</component>
			<component name="price">
				<value>20</value>
			</component>
		</inputNode>
		<inputNode name="numB">
			<value>9</value>
		</inputNode>
		<inputNode name="numC">
			<value>10</value>
		</inputNode>
		<resultNode name="priceInRange" type="decision">
			<expected>
				<value>Not in range</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="003">
		<inputNode name="dateD">
			<value xsi:type="xsd:date">2016-11-01</value>
		</inputNode>
		<resultNode name="dateCompare1" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="004">
		<inputNode name="dateD">
			<value xsi:type="xsd:date">2016-11-01</value>
		</inputNode>
		<inputNode name="dateE">
			<value xsi:type="xsd:date">2016-11-02</value>
		</inputNode>
		<resultNode name="dateCompare2" type="decision">
			<expected>
				<value>false</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== goldmansachs/jdmn/dmn-test-cases/standard/tck/1.3/nc/0015-all-any/0015-all-any-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0015-all-any.dmn</modelName>
    <labels>
        <label>Compliance Level 3</label>
        <label>Literal Expression</label>
        <label>Item Definition</label>
        <label>FEEL List</label>
        <label>FEEL Functions: lists</label>
    </labels>
    <testCase id="001">
		<inputNode name="a">
			<value>10</value>
		</inputNode>
		<inputNode name="b">
			<value>9</value>
		</inputNode>
		<inputNode name="c">
			<value>1</value>
		</inputNode>
		<resultNode name="and1" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="or1" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="literalList" type="decision">
			<expected>
				<list>
					<item>
						<value>true</value>
					</item>
					<item>
						<value>true</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="and2" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="or2" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="002">
		<inputNode name="a">
			<value>10</value>
		</inputNode>
		<inputNode name="b">
			<value>11</value>
		</inputNode>
		<inputNode name="c">
			<value>1</value>
		</inputNode>
		<resultNode name="and1" type="decision">
			<expected>
				<value>false</value>
			</expected>
		</resultNode>
		<resultNode name="or1" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="literalList" type="decision">
			<expected>
				<list>
					<item>
						<value>false</value>
					</item>
					<item>
						<value>true</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="and2" type="decision">
			<expected>
				<value>false</value>
			</expected>
		</resultNode>
		<resultNode name="or2" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>
